# Generated by Django 4.0.1 on 2022-03-08 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='first name')),
                ('last_name', models.CharField(max_length=255, verbose_name='last name')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='patronymic name')),
                ('phone', models.CharField(max_length=11, verbose_name='phone number')),
                ('age', models.IntegerField(verbose_name='age')),
                ('post_address_author', models.CharField(blank=True, max_length=255, null=True, verbose_name="author's post address")),
                ('edu_organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='educational organization name')),
                ('edu_organization_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='educational organization address')),
                ('teacher_full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='teacher full name')),
                ('teacher_position', models.CharField(blank=True, max_length=255, null=True, verbose_name="teacher's position")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=88, verbose_name='password')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('user_type', models.IntegerField(choices=[(1, 'Admin'), (2, 'Adjudicator'), (3, 'Participant')], default=3, verbose_name='user type')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
