# Generated by Django 4.0.1 on 2022-02-23 21:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_profile_userprofile_delete_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('20a5fc25-8c69-4043-8c41-b3267add0e47'), editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_address_author',
            field=models.CharField(max_length=255, null=True, verbose_name="author's post address"),
        ),
    ]
