# Generated by Django 4.0.1 on 2022-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='edu_organization_address',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='educational organization address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='post_address_author',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name="author's post address"),
        ),
    ]
