# Generated by Django 4.0.1 on 2022-03-07 09:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('556b0fc7-48b0-439f-80e2-c589e2a503c5'), editable=False, unique=True),
        ),
    ]
