# Generated by Django 4.0.1 on 2022-03-22 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='story',
            name='rate',
        ),
        migrations.AddField(
            model_name='contest',
            name='stories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest', to='contests.story'),
        ),
        migrations.AddField(
            model_name='contestrate',
            name='story',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contests.story'),
        ),
        migrations.AlterField(
            model_name='contestrate',
            name='adjudicator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
