# Generated by Django 4.0.1 on 2022-03-22 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_remove_story_contest_remove_story_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='stories',
        ),
        migrations.AddField(
            model_name='story',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='contests.contest'),
        ),
    ]
