# Generated by Django 4.0.1 on 2022-03-24 20:41

import contests.models.stories
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_remove_contest_stories_story_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='file',
            field=models.FileField(default=None, upload_to=contests.models.stories.Story._create_upload_path),
            preserve_default=False,
        ),
    ]
